# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Ioannis Petridis
description: "Hi I'm Ioannis, and I'm a Data Scientist.  My portfolio focuses on interesting projects I've recently undertaken, with a strong emphasis on business impact. I seek to apply lean Data Science and Machine Learning solutions to solve business problems and deliver impactful and innovative products within an engaging and challenging environment. I am self-directed, curious and dedicated to improve and grow both in a team and individually."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Thessaloniki, GR"
resume_url: /docs/Ioannis_Petridis_CV.pdf
avatar_image: /img/IoannisPetridis.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/ipetridis/" # Add your linkedln handle
github: "https://github.com/ispetridis"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-cayman



